import React from 'react';
import {
  StyleSheet,
} from 'react-native';
import {fontMaker} from '../components/fontMaker';

export default StyleSheet.create({
  mainContainer:{
    flex:1,
    flexDirection:'row',
    justifyContent:'space-between',
    paddingLeft:20,
    paddingRight:20,
  },
  mainContainer2:{
    flex:1,
    flexDirection:'row',
    backgroundColor:'#fbeecb',
    justifyContent:'space-between',
    paddingLeft:20,
    paddingRight:20,
  },
  textSchedule:{
  },
  textSchedule2:{
	...fontMaker({weight:'Bold'}),
  },
  flatList:{
    backgroundColor:'white',
  },
  ScrollView:{
    backgroundColor:'#e7e7e7',
  },
  isStoreOpen:{
    height:20,
    margin:10,
    marginLeft:20,
    backgroundColor:'white',
  },
  scheduleAddressContainer:{
    margin:4,
    marginBottom:0,
    backgroundColor:'white',
  },
  scheduleFlatList:{
    backgroundColor:'white',
  },
  address:{
    margin:20,
    marginBottom:10,
    backgroundColor:'white',
  },
  buttonsAndEventsView:{
    backgroundColor:'#e7e7e7',
  },
  buttonsView:{
    height:60,
    flexDirection:'row',
  },
  phoneButton:{
    flex:1,
  },
  phoneButtonView:{
    flex:1,
    borderRadius:4,
    backgroundColor:'white',
    margin:4,
    marginRight:2,
    paddingLeft:25,
    paddingRight:25,
    flexDirection:'row',
    justifyContent:'space-between',
    alignItems:'center',
  },
  phoneButtonText:{
    color:'black',
	...fontMaker({weight:'Bold'}),
  },
  mapButton:{
    flex:1,
  },
  mapButtonView:{
    flex:1,
    borderRadius:4,
    backgroundColor: 'white',
    margin:4,
    marginLeft:2,
    paddingLeft:35,
    paddingRight:35,
    flexDirection:'row',
    justifyContent:'space-between',
    alignItems:'center',
  },
  mapButtonText:{
    color:'black',
	...fontMaker({weight:'Bold'}),
  },
});
