import React from 'react';
import {
  StyleSheet,
} from 'react-native';

export default StyleSheet.create({
  row:{
    padding:0,
    paddingLeft:60,    
    marginTop:2,
    marginBottom:2,
    marginLeft:0,
    marginRight:0,
    height:60,
    flex:1,
    flexDirection:'row',
    backgroundColor:'#0000ff44',
  },
  row2:{
    padding:0,
    paddingLeft:60,    
    marginTop:2,
    marginBottom:2,
    marginLeft:0,
    marginRight:0,
    height:60,
    flex:1,
    flexDirection:'row',
    backgroundColor:'#00ff0044',
  },
  row3:{
    padding:0,
    paddingLeft:60,    
    marginTop:2,
    marginBottom:2,
    marginLeft:0,
    marginRight:0,
    height:60,
    flex:1,
    flexDirection:'row',
    backgroundColor:'#ff000044',
  },
  row4:{
    padding:0,
    paddingLeft:60,    
    marginTop:2,
    marginBottom:2,
    marginLeft:0,
    marginRight:0,
    height:60,
    flex:1,
    flexDirection:'row',
    backgroundColor:'#ffff0044',
  },
  textView:{
    backgroundColor:'white',
  },
  text:{

  },
  FLarrowImageView:{
    flex:1,
  },
  FLarrowImage:{
    flex:1,
    height:undefined,
    width:undefined,
    resizeMode:"contain",
  },
  FLrow:{
    padding:0,
    marginTop:2,
    marginBottom:2,
    marginLeft:0,
    marginRight:0,
    height:60,
    flex:1,
    flexDirection:'row',
    backgroundColor:'#ffffff',
  },
  FLtextView:{
    flex:4,
    justifyContent:'center',
  },
  FLtext:{
    fontSize:16,
  },
});